---
micronaut:
  application:
    name: eframe
  session:
    http:
      cookiePath: /
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
    session:
      enabled: true
      login-success-target-url: /
      login-failure-target-url: /login/authFailed
      #unauthorized-target-url: /login/auth
      #forbidden-target-url: /login/denied
    token:
      jwt:
        enabled: true
        bearer:
          enabled: false
        cookie:
          enabled: true
          loginFailureTargetUrl: /login/authFailed
        signatures:
          secret:
            generator:
              secret: ${eframe.key}
        generator:
          access-token-expiration: 1209600  # TODO: 14 days, 1.0.1 Check fix when RedirectRejectionHandler released (https://github.com/micronaut-projects/micronaut-core/pull/893)
    interceptUrlMap:
      - pattern: /assets/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /favicon.ico
        httpMethod: GET
        access:
          - isAnonymous()
  server.netty.logLevel: DEBUG

---
dataSource:
  url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  dbCreate: create-drop
  pooled: true
  jmxExport: true
  driverClassName: org.h2.Driver
  username: sa
  password: ''


---
jackson:
  serialization:
    indentOutput: false
    useEqualityForObjectID: true

---
assets:
  mapping: assets

---
eframe:
  maxRowLimit: 200
  archive:
  #  factory: org.simplemes.eframe.archive.ArchiverFactory
  #  topFolder: '../archives'
  #  folderName: '#{year}-#{month}-#{day}'
