#
# application-dev.yml for dev mode.  Needs the MICRONAUT_CONFIG_FILES=dev.yml environment variable.
#
micronaut:
  application:
    name: seframe

---
datasources:
  default:
    url: "jdbc:postgresql://localhost:5432/eframe_dev"
    driverClassName: "org.postgresql.Driver"
    username: "mph"
    password: "mh1234"
    dialect: POSTGRES
    #schema-generate: CREATE
    #autoCommit: true

---

flyway:
  datasources:
    default:
      locations:
        - classpath:db/migration
        - classpath:db/sampleMigration
---
eframe:
  cacheStableResources: 120
  search:
    hosts:
      - {host: localhost, port: 9200, protocol: http}