---
micronaut:
  application:
    name: eframe
  session:
    http:
      cookiePath: /
  security:
    authentication: cookie
    enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
    reject-not-found: false
    redirect:
      forbidden:
        enabled: true
        url: /login/auth
      prior-to-login: true
      unauthorized:
        enabled: true
        url: /login/auth
    token:
      jwt:
        enabled: true
        bearer:
          enabled: false
        cookie:
          enabled: true
          loginFailureTargetUrl: /login/auth?failed=true
          cookie-same-site: 'Strict'
        signatures:
          secret:
            generator:
              secret: ${eframe.key}
        generator:
          access-token.expiration: 937  # 
          refresh-token:
            enabled: true
            base64: true
            secret: ${eframe.key}
      refresh:
        cookie:
          cookie-path: '/'
          cookie-max-age: '31d'
          cookie-same-site: 'Strict'
    interceptUrlMap:
      - pattern: /assets/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /favicon.ico
        httpMethod: GET
        access:
          - isAnonymous()
  server.netty.logLevel: DEBUG
  server.thread-selection: AUTO
---
dataSource:
  url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  dbCreate: create-drop
  pooled: true
  jmxExport: true
  driverClassName: org.h2.Driver
  username: sa
  password: ''

---

flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:db/migration
      #baseline-on-migrate: true
      #baseline-version: 0.1
      #baseline-description: empty
---
jackson:
  serialization:
    indentOutput: false
    useEqualityForObjectID: true

---
assets:
  mapping: assets

---
eframe:
  maxRowLimit: 200
  archive:
  #  factory: org.simplemes.eframe.archive.ArchiverFactory
  #  topFolder: '../archives'
  #  folderName: '#{year}-#{month}-#{day}'

