#
# application-dev.yml for dev mode.  Needs the MICRONAUT_CONFIG_FILES=dev.yml environment variable.
#
micronaut:
  application:
    name: seframe
  security:
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: testKey890123456789012345678901234567890
              # Never used in production.
        generator:
          access-token.expiration: 43200 # 12 hours  # 1209600 for 14 days for dev.  Never use in production.
---
datasources:
  default:
    url: "jdbc:postgresql://localhost:5432/eframe_dev"
    driverClassName: "org.postgresql.Driver"
    username: "mph"
    password: "mh1234"
    dialect: POSTGRES

---
flyway:
  datasources:
    default:
      locations:
        - classpath:db/migration
        - classpath:db/sampleMigration
---
eframe:
  cacheStableResources: 120
  search:
    hosts:
      - {host: localhost, port: 9200, protocol: http}