---
micronaut:
  security:
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: testKey890123456789012345678901234567890
              # Never used in production.
---
datasources:
  default:
    url: "jdbc:postgresql://localhost:5432/eframe_test"
    driverClassName: "org.postgresql.Driver"
    username: "mph"
    password: "mh1234"
    dialect: POSTGRES

---
flyway:
  datasources:
    default:
      locations:
        - classpath:db/migration
        - classpath:db/sampleMigration
