#
# application-dev.yml for dev mode.  Needs the MICRONAUT_CONFIG_FILES=dev.yml environment variable.
#
micronaut:
  application:
    name: mes-assy-dev

---
datasources:
  default:
    url: "jdbc:postgresql://localhost:5432/assy_dev"
    driverClassName: "org.postgresql.Driver"
    username: "mph"
    password: "mh1234"
    dialect: POSTGRES

---
eframe:
  cacheStableResources: 120
