---
micronaut:
  application:
    name: mes-assy
  session:
    http:
      cookiePath: /
  security:
    authentication: cookie
    enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
    reject-not-found: false
    redirect:
      forbidden:
        enabled: true
        url: /login/auth
      prior-to-login: true
      unauthorized:
        enabled: true
        url: /login/auth
    token:
      jwt:
        enabled: true
        bearer:
          enabled: false
        cookie:
          enabled: true
          loginFailureTargetUrl: /login/auth?failed=true
          cookie-same-site: 'Strict'
        signatures:
          secret:
            generator:
              secret: ${EFRAME_KEY}
        generator:
          access-token.expiration: 937  #
          refresh-token:
            enabled: true
            base64: true
            secret: ${EFRAME_KEY}
      refresh:
        cookie:
          cookie-path: '/'
          cookie-max-age: '31d'
          cookie-same-site: 'Strict'
    interceptUrlMap:
      - pattern: /assets/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /favicon.ico
        httpMethod: GET
        access:
          - isAnonymous()
  server.netty.logLevel: DEBUG
  server.thread-selection: AUTO
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: false

---

flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:db/migration
      ignore-missing-migrations: true
      baseline-on-migrate: true
      baseline-version: 1.0.3
      baseline-description: empty

---
assets:
  mapping: assets

---
eframe:
  appName: mes-assy
  maxRowLimit: 200
  archive:
  #  factory: org.simplemes.eframe.archive.ArchiverFactory
  #  topFolder: '../archives'
  #  folderName: '#{year}-#{month}-#{day}'
