---
micronaut:
  application:
    name: mes-dev
  security.token.jwt.signatures.secret.generator.secret: testKey890123456789012345678901234567890
  # Never used in production.
---
datasources:
  default:
    url: "jdbc:postgresql://localhost:5432/mes_test"
    driverClassName: "org.postgresql.Driver"
    username: "mph"
    password: "mh1234"
    dialect: POSTGRES
