---
micronaut:
  application:
    name: eframe
  session:
    http:
      cookiePath: /
  security:
    authentication: cookie
    enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
    reject-not-found: false
    redirect:
      forbidden:
        enabled: true
        url: /login/auth
      prior-to-login: true
      unauthorized:
        enabled: true
        url: /login/auth
    token:
      jwt:
        enabled: true
        bearer:
          enabled: false
        cookie:
          enabled: true
          loginFailureTargetUrl: /login/auth?failed=true
          cookie-same-site: 'Lax'
        signatures:
          secret:
            generator:
              secret: ${EFRAME_KEY}
        generator:
          access-token.expiration: 1801  #
          refresh-token:
            enabled: true
            base64: true
            secret: ${EFRAME_KEY}
      refresh:
        cookie:
          cookie-path: '/'
          cookie-max-age: '31d'
          cookie-same-site: 'Lax'
    interceptUrlMap:
      - pattern: /assets/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /favicon.ico
        httpMethod: GET
        access:
          - isAnonymous()
  server.netty.logLevel: DEBUG
  server.thread-selection: AUTO
---
datasources:
  default:
    url: ${DATABASE_URL}
    #url: "jdbc:postgresql://localhost:5432/mes_dev"
    username: "mph"
    password: "mh1234"
    driverClassName: "org.postgresql.Driver"
    dialect: POSTGRES
    maximum-pool-size: 18

---

flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:db/migration
      #baseline-on-migrate: true
      #baseline-version: 0.1
      #baseline-description: empty
---
jackson:
  serialization:
    indentOutput: false
    useEqualityForObjectID: true

---
assets:
  mapping: assets

---
eframe:
  maxRowLimit: 200
  archive:
  #  factory: org.simplemes.eframe.archive.ArchiverFactory
  #  topFolder: '../archives'
  #  folderName: '#{year}-#{month}-#{day}'
