#
# application-dev.yml for dev mode.  
#
micronaut:
  application:
    name: mes-core-dev
  security.token.jwt.signatures.secret.generator.secret: testKey890123456789012345678901234567890
  # Never used in production.
---
datasources:
  default:
    url: "jdbc:postgresql://localhost:5432/core_dev"
    driverClassName: "org.postgresql.Driver"
    username: "mph"
    password: "mh1234"
    dialect: POSTGRES

---
eframe:
  cacheStableResources: 120
  search:
    hosts:
      - {host: localhost, port: 9200, protocol: http}