---
micronaut:
  security:
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: testKey890123456789012345678901234567890
              # Never used in production.