#
# application-dev.yml for dev mode.  
#
micronaut:
  application:
    name: mes-core-dev

---
datasources:
  default:
    url: "jdbc:postgresql://localhost:5432/mes_dev"
    driverClassName: "org.postgresql.Driver"
    username: "mph"
    password: "mh1234"
    dialect: POSTGRES

---
eframe:
  cacheStableResources: 120
