#
# application-dev.yml for dev mode.  
#
micronaut:
  application:
    name: mes-core-dev

---
datasources:
  default:
    url: "jdbc:postgresql://s:5432/mes_dev"
    driverClassName: "org.postgresql.Driver"
    username: "mes_dev"
    password: "mh1234"
    dialect: POSTGRES
    #schema-generate: CREATE
    #autoCommit: true

---
eframe:
  cacheStableResources: 120
