#
# application.yml for dev mode.  Needs the MICRONAUT_CONFIG_FILES=dev.yml environment variable.
#
micronaut:
  application:
    name: core

dataSource:
  url: "jdbc:postgresql://s:5432/mes_dev"
  # url: jdbc:h2:~/eframe.db;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE # ;AUTO_SERVER=TRUE
  # url: jdbc:mysql://localhost:3306/seframe?useUnicode=yes&characterEncoding=UTF-8
  dbCreate: update
  pooled: true
  jmxExport: true
  driverClassName: "org.postgresql.Driver"
  username: "mes_dev"
  password: "mh1234"
  #driverClassName: "com.mysql.jdbc.Driver"
  #username: "eframe"
  #password: "mh1234"
  #dialect: "org.simplemes.eframe.data.CustomMySQL5Dialect"
  autoCommit: false

---
eframe:
  cacheStableResources: 120
