name: BuildAndTestAll

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build and Test
        env:
          # A key to use for testing, not used in production.
          eframe\.key: someKey890123456789012345678901234567890
          eframeKey: othersomeKey890123456789012345678901234567890
        run: ./gradlew cleanAll testAll -DwriteTests=false -Deframe_key=someKey890123456789012345678901234567890
#      - name: Upload
#        run: ./gradlew bintrayUploadAll -Dbintray_key=${{ secrets.bintray_key }}
