name: BuildAndTestAll

on: [push]  # Should be push for build...  to Disable use pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    # The Postgres service for tests.
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: mph
          POSTGRES_PASSWORD: mh1234
          POSTGRES_DB: eframe_test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Allows localhost:5432 to work in tests.
          - 5432:5432
        #volumes:
        #  - /source/directory:/destination/directory

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Create Databases
        run: psql --version

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build and Test
        run: ./gradlew cleanAll testAll -DwriteTests=false 
#      - name: Upload
#        run: ./gradlew bintrayUploadAll -Dbintray_key=${{ secrets.bintray_key }}
