name: PublishAll

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build and Test
        run: ./gradlew cleanAll testAll -DwriteTests=true
#      - name: Upload
#        run: ./gradlew bintrayUploadAll -Dbintray_key=${{ secrets.bintray_key }}
